
public class Zoznam {
String[][] zoznam =
{
{"Jerguö","ADAMEC"},
{"KatarÌna","ACHBERGEROV¡"},
{"Tom·ö","BAKOä"},
{"ätefan","BAR»ÕK"},
{"SoÚa","BARTEKOV¡"},
{"K·roly","BELOKOSTOLSK›"},
{"Jakub","BI»IAN"},
{"Tam·s","BILEK"},
{"Ladislav","BILISICS"},
{"Martin","BOHUMEL"},
{"Ingrid","BOHUNICK¡"},
{"Michal","BRCKO"},
{"Matej","BUZ¡ä"},
{"Tam·s","DANIS"},
{"Martin","DEMETER"},
{"Nat·lia","œURISOV¡"},
{"KatarÌna","FABIANOV¡"},
{"SabÌna","FA»KOVCOV¡"},
{"Peter","FRçALA"},
{"Jaroslav","F⁄SKA"},
{"Richard","GUçAN"},
{"Gabriel","HALASI"},
{"Adam","HAL¡SZ"},
{"Roman","HANZLÕK"},
{"Jana","HARVANOV¡"},
{"Martin","HEINZ"},
{"Peter","HLATKY"},
{"Michal","HOºUKA"},
{"Kl·ra","HORV¡THOV¡"},
{"Patrik","HUD¡K"},
{"Ondrej","HUS¡R"},
{"Jaroslav","IäTOK"},
{"Martina","JAMRIäKOV¡"},
{"Timotej","JUR¡äEK"},
{"Patrik","KATRINEC"},
{"Martin","KELLNER"},
{"Michal","KLEIN"},
{"Filip","KOV¡»"},
{"Tibor","KRAJCZ¡R"},
{"Veronika","KRAJ»OVICOV¡"},
{"Ferdinand","KRIéAN"},
{"Eva","KUNOVSK¡"},
{"Roman","KURUC"},
{"Ivan","LATT¡K"},
{"Peter","MAG¡T"},
{"Martin","MAäEK"},
{"M·ria","M…RIOV¡"},
{"KristÌna","MIKLOäOV¡"},
{"Samuel","MITAS"},
{"ätefan","ORTUTAY"},
{"Michal","PANDULA"},
{"Michael","PAVELKA"},
{"Daniel","PETHES"},
{"Michal","PIJ¡K"},
{"Michal","PUäKEL"},
{"Matej","RANDÕK"},
{"Martin","REGULY"},
{"RÛbert","RUSKA"},
{"Martin","SADLO“"},
{"Mari·n","SKRIP"},
{"Tom·ö","SL¡MA"},
{"Vlastimil","STAREC"},
{"Duöan","SUJA"},
{"Alexander","SZENDY"},
{"Martin","äOMODI"},
{"Filip","äPALDO“"},
{"Jakub","TRUBA»"},
{"Viliam","VAKERMAN"},
{"Michaela","V¡VROV¡"},
{"Matej","VILK"},
{"Samuel","WENDL"}
}
;

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
